Chore: handle user in webhooks
internxt/payments pull request #71
Opened 2024-07-08 20:34 UTC by evillalba94

### Update
- Getting the `user` on webhooks. The user must be captured to continue with the operations (**update storage**, **space**, etc), when paying for a `business subscription` it is difficult to obtain the user since it has not yet been created if there is NOT a `subscription individual/personal` before, so it is necessary to verify that the user exists but rather create it.

- To create it, the `user.uuid` is required, however, if the user is not registered in the **payments database** then we will have to search for it on the `drive-server`. For this reason, a **New Endpoint** was created in `drive-server` that allows us to search for the user through the email provided by `Stripe.Customer`.

### PR related
-

2024-07-09 09:39 UTC, sg-gs commented
As we are integrating this change on the branch that will be released together with Drive's Workspaces, why are we still using the old gateway? drive-server is a deprecated project and we will avoid making changes there @evillalba94

2024-07-09 09:53 UTC, sg-gs requested changes

2024-07-09 09:53 UTC, sg-gs commented on src/webhooks/handleSubscriptionUpdated.ts
I can accept the changes on the checkout session completed, but not on the subscription updated. If the user has a subscription, it should exist on this service and is a mandatory condition. Otherwise, we should fix that anomaly in other ways like the support service, which is out of the scope of the payments service, therefore I would just remove the changes done here.

2024-07-09 16:02 UTC, evillalba94 commented
The implementation will not take place. If necessary, it will be carried out in the most current drive project.

> As we are integrating this change on the branch that will be released together with Drive's Workspaces, why are we still using the old gateway? drive-server is a deprecated project and we will avoid making changes there @evillalba94

Done! I made the changes to use `drive-server-wip`. PR related: https://github.com/internxt/drive-server-wip/pull/354

2024-07-10 09:05 UTC, sg-gs approved these changes

2024-07-10 09:05 UTC, merged